# Generated by Django 4.2 on 2024-04-27 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descripion',
            new_name='description',
        ),
    ]
