# Generated by Django 4.2 on 2024-04-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_descripion_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marque',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
