# Generated by Django 4.2.6 on 2024-05-09 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="birthday",
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
