# Generated by Django 4.2.6 on 2024-05-09 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_account_birthday"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="phone_number",
        ),
    ]
