# Generated by Django 4.2.6 on 2024-05-30 23:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_account_phone_number_account_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="account",
            name="profile_pic",
        ),
    ]
